module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "colors-component-general-border-color":
          "var(--colors-component-general-border-color)",
        "colors-grayscale-gray-200": "var(--colors-grayscale-gray-200)",
        "colors-grayscale-gray-600": "var(--colors-grayscale-gray-600)",
        "colors-theme-body-bg": "var(--colors-theme-body-bg)",
        "colors-theme-body-color": "var(--colors-theme-body-color)",
        "colors-theme-heading-color": "var(--colors-theme-heading-color)",
        "colors-theme-primary": "var(--colors-theme-primary)",
        company: "var(--company)",
        footor: "var(--footor)",
        "grey-30": "var(--grey-30)",
        "grey-secondary": "var(--grey-secondary)",
        "header-color": "var(--header-color)",
        line: "var(--line)",
        people: "var(--people)",
        "primary-cta": "var(--primary-cta)",
        product: "var(--product)",
        project: "var(--project)",
        "variable-collection-blck": "var(--variable-collection-blck)",
        "variable-collection-color": "var(--variable-collection-color)",
        "variable-collection-CPS-dark-grey":
          "var(--variable-collection-CPS-dark-grey)",
        "variable-collection-CPS-white": "var(--variable-collection-CPS-white)",
        "variable-collection-white-80": "var(--variable-collection-white-80)",
        "white-bg": "var(--white-bg)",
        "white-bg-40": "var(--white-bg-40)",
        "white-bg-60": "var(--white-bg-60)",
        "white-bg-80": "var(--white-bg-80)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "body-regular": "var(--body-regular-font-family)",
        "body-small": "var(--body-small-font-family)",
        "body-text": "var(--body-text-font-family)",
        "button-text": "var(--button-text-font-family)",
        "button-underline": "var(--button-underline-font-family)",
        close: "var(--close-font-family)",
        "home-button": "var(--home-button-font-family)",
        "light-big": "var(--light-big-font-family)",
        "main-headers": "var(--main-headers-font-family)",
        short: "var(--short-font-family)",
        small: "var(--small-font-family)",
        "SUB-bold": "var(--SUB-bold-font-family)",
        "sub-headers": "var(--sub-headers-font-family)",
        "SUB-light": "var(--SUB-light-font-family)",
        "tagline-notes": "var(--tagline-notes-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: { "light-medium": "var(--light-medium)" },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
